# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [99]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [100]:
# Create a 1-dimensional NumPy array using np.array()
single=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
double=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
triple=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [101]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
single.shape,single.ndim,single.dtype,single.size,type(single)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [102]:
# Attributes of 2-dimensional array
double.shape,double.ndim,double.dtype,double.size,type(double)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [103]:
# Attributes of 3-dimensional array
triple.shape,triple.ndim,triple.dtype,triple.size,type(triple)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [104]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(double)
df

0  1  2
0  1  2  3
1  4  5  6

In [105]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [106]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [107]:
# Create an array within a range of 0 and 100 with step 3
a1=np.arange(0,100,3)
a1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [108]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array=np.random.randint(0,10,size=(7,2))
random_array

array([[6, 4],
       [0, 0],
       [2, 1],
       [4, 9],
       [5, 6],
       [3, 6],
       [7, 0]], dtype=int32)

In [109]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array2=np.random.random((3,5))
random_array2

array([[0.72821635, 0.36778313, 0.63230583, 0.63352971, 0.53577468],
       [0.09028977, 0.8353025 , 0.32078006, 0.18651851, 0.04077514],
       [0.59089294, 0.67756436, 0.01658783, 0.51209306, 0.22649578]])

In [110]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array3=np.random.randint(0,10,size=(4,6))
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [111]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_numbers=np.random.randint(1,10,size=(3,7))
# Find the unique numbers in the array you just created
np.unique(random_numbers)

array([1, 2, 3, 4, 5, 7, 9], dtype=int32)

In [112]:
# Find the 0'th index of the latest array you created
random_numbers[0]

array([9, 1, 3, 7, 4, 9, 3], dtype=int32)

In [113]:
# Get the first 2 rows of latest array you created
random_numbers[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [114]:
# Get the first 2 values of the first 2 rows of the latest array
random_numbers[:2,:2]

array([[9, 1],
       [5, 3]], dtype=int32)

In [115]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a4=np.random.randint(10,size=(3,5))
one=np.ones((3,5))

In [116]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [117]:
# Add the two arrays together
a4+one

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [118]:
# Create another array of ones of shape (5, 3)
ones=np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [119]:
# Try add the array of ones and the other most recent array together
# transpose matrix one because of its shape
ones+one.T

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [120]:
# Create another array of ones of shape (3, 5)
new_ones=np.ones((3,5))
new_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [121]:
# Subtract the new array of ones from the other most recent array
new_ones-one

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [122]:
# Multiply the ones array with the latest array
new_ones*one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [123]:
# Take the latest array to the power of 2 using '**'
a4**2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [124]:
# Do the same thing with np.square()
np.square(a4)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [125]:
# Find the mean of the latest array using np.mean()
np.mean(a4)

np.float64(3.8666666666666667)

In [126]:
# Find the maximum of the latest array using np.max()
np.max(a4)

np.int32(9)

In [127]:
# Find the minimum of the latest array using np.min()
np.min(a4)

np.int32(0)

In [128]:
# Find the standard deviation of the latest array
np.std(a4)

np.float64(2.578543947441829)

In [129]:
# Find the variance of the latest array
np.var(a4)

np.float64(6.648888888888889)

In [130]:
# Reshape the latest array to (3, 5, 1)
a4.reshape(3,5,1),a4.shape

(array([[[6],
         [7],
         [2],
         [0],
         [3]],
 
        [[1],
         [7],
         [3],
         [1],
         [5]],
 
        [[5],
         [9],
         [3],
         [5],
         [1]]], dtype=int32),
 (3, 5))

In [131]:
# Transpose the latest array
a4.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]], dtype=int32)

What does the transpose do?

In [132]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
r1=np.random.randint(10,size=(3,3))
r2=np.random.randint(10,size=(3,2))
r1,r2

(array([[9, 1, 9],
        [3, 7, 6],
        [8, 7, 4]], dtype=int32),
 array([[1, 4],
        [7, 9],
        [8, 8]], dtype=int32))

In [133]:
# Perform a dot product on the two newest arrays you created
r1.dot(r2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]], dtype=int32)

In [134]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
r1=np.random.randint(10,size=(4,3))
r2=np.random.randint(10,size=(4,3))
r1,r2

(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2],
        [0, 7, 2]], dtype=int32),
 array([[2, 0, 4],
        [9, 6, 9],
        [8, 6, 8],
        [7, 1, 0]], dtype=int32))

In [135]:
# Perform a dot product on the two newest arrays you created
np.dot(r1,r2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
r2=r2
np.dot(r1,r2)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,10,(2,2))

In [ ]:
# Compare the two arrays with '>'
a>b

array([[False, False],
       [False, False]])

What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='
a>=b

array([[False, False],
       [ True, False]])

In [ ]:
# Find which elements of the first array are greater than 7
a>7

array([[False, False],
       [ True, False]])

In [ ]:
# Which parts of each array are equal? (try using '==')
a==b

array([[False, False],
       [ True, False]])

In [ ]:
# Sort one of the arrays you just created in ascending order
np.sort(a)

array([[0, 4],
       [6, 9]], dtype=int32)

In [ ]:
# Sort the indexes of one of the arrays you just created
np.argsort(a)

array([[0, 1],
       [1, 0]])

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a)

np.int64(2)

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a)

np.int64(0)

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a4,axis=1)

array([1, 1, 1])

In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a4,axis=0)

array([1, 0, 0, 0, 2])

In [ ]:
# Create an array of normally distributed random numbers
c=np.random.randn(3,5)
c

array([[ 1.94511561, -0.15333646, -0.90698723, -0.81735416, -0.48312268],
       [-0.56982835, -2.09159967,  1.26374053, -0.01548334, -0.02737645],
       [ 0.81787351, -1.05460447, -0.75832712,  0.45741565, -0.06437805]])

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.